name: Naver Paper Python GitHub Actions
on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt-get install -y gdebi-core
        sudo gdebi google-chrome-stable_current_amd64.deb        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        mkdir -p ~/.naver
        echo "[default]" > ~/.naver/credentials
        echo "username = " $USERNAME >> ~/.naver/credentials
        echo "password = " $PASSWORD >> ~/.naver/credentials
        python run_new.py
      env:
        USERNAME: ${{ secrets.ID }} # secret에 저장된 내용을 불러옴
        PASSWORD: ${{ secrets.PASSWORD }}
